export const brandDatas: BrandType[] = [
  { id: 1, brandId: 0, name: '&TRADITION', englishName: 'andtradition', koreanName: '앤트레디션' },
  { id: 2, brandId: 0, name: 'A COLD WALL', englishName: 'acoldwall', koreanName: '어콜드월' },
  { id: 3, brandId: 0, name: 'BA&SH', englishName: 'bash', koreanName: '바쉬' },
  { id: 4, brandId: 0, name: 'C.P. COMPANY', englishName: 'cpcompany', koreanName: '씨피컴퍼니' },
  { id: 5, brandId: 0, name: 'D ACOUSTICS', englishName: 'dacoutics', koreanName: '디어쿠스틱스' },
  { id: 6, brandId: 0, name: 'EASTERN EDITION', englishName: 'easternedition', koreanName: '이스턴에디션' },
  { id: 7, brandId: 0, name: '4GIVENESS', englishName: 'forgiveness', koreanName: '포기브니스' },
  { id: 8, brandId: 0, name: 'G-CUT', englishName: 'gcut', koreanName: '지컷' },
  { id: 9, brandId: 0, name: 'H COUTURE', englishName: 'hcouture', koreanName: '에이치꾸뛰르' },
  { id: 10, brandId: 0, name: 'I HATE MONDAY', englishName: 'ihatemonday', koreanName: '아이헤이트먼데이' },
  { id: 11, brandId: 0, name: 'J.CHUNG', englishName: 'jchung', koreanName: '제이청' },
  { id: 12, brandId: 0, name: 'K-WAY', englishName: 'kway', koreanName: '까웨' },
  { id: 13, brandId: 0, name: 'L&C STENDAL', englishName: 'landcstendal', koreanName: '엘앤씨 스텐달' },
  { id: 14, brandId: 0, name: 'MAC', englishName: 'mac', koreanName: '맥' },
  { id: 15, brandId: 0, name: 'N.C.P', englishName: 'ncp', koreanName: '엔씨피' },
  { id: 16, brandId: 0, name: '1O7', englishName: 'oneoseven', koreanName: '원오세븐' },
  { id: 17, brandId: 0, name: 'PACO RABANNE', englishName: 'pacorabanne', koreanName: '파코라반' },
  { id: 18, brandId: 0, name: 'QUA-T', englishName: 'quat', koreanName: '콰티' },
  { id: 19, brandId: 0, name: 'R13', englishName: 'rthirteen', koreanName: '알썰틴' },
  { id: 20, brandId: 0, name: 'S.T. DUPONT', englishName: 'stdupont', koreanName: '듀퐁' },
  { id: 21, brandId: 0, name: 'T.A.P', englishName: 'tao', koreanName: '타오' },
  { id: 22, brandId: 0, name: 'UGG', englishName: 'ugg', koreanName: '어그' },
  { id: 23, brandId: 0, name: 'VALENTINO', englishName: 'valentino', koreanName: '발렌티노' },
  { id: 24, brandId: 0, name: 'WANDLER', englishName: 'wandler', koreanName: '반들러' },
  { id: 25, brandId: 0, name: 'XC', englishName: 'xc', koreanName: '엑스씨' },
  { id: 26, brandId: 0, name: 'Y-3', englishName: 'ythree', koreanName: '와이쓰리' },
  { id: 27, brandId: 0, name: 'ZADIG&VOLTAIRE', englishName: 'zadigandvoltaire', koreanName: '쟈딕앤볼테르' },
  { id: 28, brandId: 0, name: '032C', englishName: '032c', koreanName: '032씨' },
  { id: 29, brandId: 0, name: '한국금거래소', koreanName: '한국금거래소' },
  { id: 30, brandId: 0, name: 'GALLERY NAREE', englishName: 'gallerynaree', koreanName: '나리화랑' },
  { id: 31, brandId: 0, name: `L'AIR DE SAVON`, englishName: 'lairdesavon', koreanName: '레르 드 사봉' },
  { id: 32, brandId: 0, name: 'CHAIR GALLERY', englishName: 'chairgallery', koreanName: '체어갤러리' },
  { id: 33, brandId: 0, name: 'CADO', englishName: 'cado', koreanName: '카도' },
  { id: 34, brandId: 0, name: 'FILA', englishName: 'fila', koreanName: '휠라' },
]
