#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(:[\w-]+:)(init|feat|test|fix|docs|style|refactor|perf|build|ci|chore|revert): .+$"

# Use grep with Perl-compatible regex for emoji support
if ! echo "$message" | grep -Pq "$requiredPattern"; then
  echo "=========================================================================="
  echo "======================   🚨 WRONG COMMIT MESSAGE!   ======================"
  echo "=========================================================================="
  echo "== Format should be => [emoji][type]: [subject]                         =="
  echo "== Allowed Types: init, feat, test, fix, docs, style, refactor, perf, build, ci, chore, revert =="
  echo "== EXAMPLE => :emoji_name:feat: Add new feature                         =="
  echo "=========================================================================="
  echo "== Your commit message was => $message "
  echo "== For more information, check script in .husky/commit-msg or README.md =="
  echo "=========================================================================="
  exit 1
else
  echo "=========================================================================="
  echo "=======================      COMMIT CREATED!!      ======================="
  echo "=========================================================================="
fi